### PR TITLE
Added a button to select the file from a file dialog window rather than manually typing it in

### PR DESCRIPTION
**Pull request by MohsenA437**
I found it a bit annoying to constantly have to type in the file path for the file I wanted to compare to, so I added a button that when clicked, will open a file dialog window that allows you to select the file instead.

### CODE REVIEW

**Comment by StudioLE** [comment]
Thanks for implementing this, it was quite high on my agenda.

I've got a couple of comments that I'll add, then once resolved I'll look to merge this as part of a wider refactor.

**Comment by StudioLE** [comment]
Would you be able to amend the commit to only include the file dialog/file selection logic? I'm reluctant to include the ChangedNodesDictionary you're defining because it conflicts with other planned changes.

**Comment by MohsenA437** [comment]
Sure I can do that, I was planning on reworking it because what I had
planned didn't seem to work either.

**Comment by StudioLE** [comment]
> Sure I can do that, I was planning on reworking it because what I had planned didn't seem to work either.


I think your line https://github.com/arcadishackathon/TrainWreck/pull/12/commits/ebf4dcd4ed9bf84be68396f6cd9fcdfd67bd03b2#diff-42fb6e4b26ac1dade2b6c0166b366b6eR126

```c#
 IEnumerable<string> changedNodes = referenceNodeDict.Keys.Intersect(currentNodeDict.Keys);
```
is just doing the same thing as https://github.com/arcadishackathon/TrainWreck/pull/12/commits/ebf4dcd4ed9bf84be68396f6cd9fcdfd67bd03b2#diff-42fb6e4b26ac1dade2b6c0166b366b6eR124
```c#
IEnumerable<string> remainingNodes = currentNodeDict.Keys.Except(addedNodes.ToList());
```
but by another method.

It's selecting all the node GUIDs that exist in both the current and reference graphs. The ModifiedNodes method will need to be more explicit and look at the nodes themselves and determine where input values, data values, lacing and many more possible values have changed.

**Comment by MohsenA437** [comment]
Yes that was one thing that I found out, I didn't get a chance to test it
out too much recently. Did you guys have ideas on checks?

**Comment by StudioLE** [comment]
I've implemented the file browse/selection in commit 51a8b014e4395fa0e74f2546389956803cc562b4 (I've added you as a co-author, thanks!). It's currently on the `refactor` branch #13. It'll be merged into the master at some point in the future.

**Pull request closed without merging**
